# Use the official MySQL image as a parent image
FROM mysql:latest

# Set environment variables for MySQL root user password
ENV MYSQL_ROOT_PASSWORD=rootpassword

# Set environment variables for database name, user, and password
ENV MYSQL_DATABASE=erp
ENV MYSQL_USER=erpuser
ENV MYSQL_PASSWORD=password

# Copy the SQL initialization script into the container
COPY ./init.sql /docker-entrypoint-initdb.d/